### PR TITLE
Update documentation link

### PR DESCRIPTION
**Pull request by amuniz**
@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by recena** [comment]
:bee:

**Comment by jglick** [comment]
Uh, why did you file a PR against _your own fork_?

**Comment by amuniz** [comment]
oh my

**Pull request closed without merging**
